# Analyzing the Autism Prevalence

In [2]:
# Import Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re
from datetime import datetime

Read csv files to Dataframe

CSV 1

In [13]:
# Read Autism prevalance around the world
asd_world = pd.read_csv("../data/autism_prevalence_studies.csv")
asd_world.head()

,Author,Title,Year Published,Country,Area(s),Age Range,Study Years,Case Identification Method,Case Criterion,Sample Size,...,Diagnosis Age Range (months),Diagnosis Mean Age (months),Diagnosis Median Age (months),IQ Score <70 (%),Adaptive Score <70 (%),Non-Verbal or Minimally Verbal (%),Percentage of Individual Co-occurring Conditions,Autism Types Included,Link to Publication,CDC Calculated Values
0,Lotter,Epidemiology of Autistic Conditions in Young C...,1966,England,County of Middlesex,8 to 10,1964,survey (mail); health records,Kanner,78000.0,...,NaN,NaN,NaN,84.0,NaN,59.0,NaN,autistic conditions,https://link.springer.com/article/10.1007/BF00...,IQ Score <70 (%); CI
1,Treffert,Epidemiology of infantile Autism,1970,USA,Wisconsin,2 to 12,1962-1967,health records,Kanner,899750.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,classic infantile autism,https://www.ncbi.nlm.nih.gov/pubmed/5436867,CI
2,Brask,A Prevalence investigation of Childhood Psychoses,1972,Denmark,Åarhus County,2 to 14,1962,health records; service provider records,clinical interpretation,46500.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,autistic syndrome,NaN,CI
3,"Wing, et al.",The prevalence of early childhood autism: comp...,1976,England,Camberwall,5 to 14,1974,registry; survey (unspecified),clinical interpretation,25000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,early childhood autism,https://pubmed.ncbi.nlm.nih.gov/935299/,CI
4,"Wing, et al.",Severe impairments of social interaction and a...,1979,England,Camberwell,0 to 14,1970,registry; service provider records,Kanner; clinical interpretation,35000.0,...,NaN,NaN,NaN,70.0,NaN,59.0,0 (Down syndrome),autism,https://www.ncbi.nlm.nih.gov/pubmed/155684,IQ Score <70 (%); CI

In [55]:
asd_world.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 207 entries, 0 to 206
Data columns (total 26 columns):
 #   Column                                            Non-Null Count  Dtype
---  ------                                            --------------  -----
 0   Author                                            207 non-null    object
 1   Title                                             207 non-null    object
 2   Year Published                                    207 non-null    int64
 3   Country                                           207 non-null    object
 4   Area(s)                                           202 non-null    object
 5   Age Range                                         202 non-null    object
 6   Study Years                                       185 non-null    object
 7   Case Identification Method                        207 non-null    object
 8   Case Criterion                                    207 non-null    object
 9   Sample Size                                       192 non-null    float64
 10  Number of Cases                                   192 non-null    float64
 11  ASD Prevalence Estimate per 1,000                 207 non-null    float64
 12  Confidence Interval (CI)                          184 non-null    object
 13  Male:Female Sex Ratio                             139 non-null    float64
 14  Non-Hispanic White:Hispanic Prevalence Ratio      30 non-null     float64
 15  White:Black Prevalence Ratio                      34 non-null     float64
 16  Diagnosis Age Range (months)                      9 non-null      object
 17  Diagnosis Mean Age (months)                       14 non-null     float64
 18  Diagnosis Median Age (months)                     25 non-null     object
 19  IQ Score <70 (%)                                  68 non-null     float64
 20  Adaptive Score <70 (%)                            1 non-null      float64
 21  Non-Verbal or Minimally Verbal (%)                13 non-null     float64
 22  Percentage of Individual Co-occurring Conditions  37 non-null     object
 23  Autism Types Included                             207 non-null    object
 24  Link to Publication                               205 non-null    object
 25  CDC Calculated Values                             207 non-null    object
dtypes: float64(10), int64(1), object(15)
memory usage: 42.2+ KB

In [63]:
asd_world_count =  asd_world.groupby('Country')['Number of Cases'].sum().sort_values(ascending=False).reset_index()
asd_world_count.head()

   Country  Number of Cases
0      USA         745934.0
1  England         121913.0
2   Sweden          43888.0
3    Korea          35529.0
4   Canada          23330.0

In [33]:
# Read Cumulative Incidence Data
cumulative_incidence = pd.read_csv("../data/Cumulative Incidence Data.csv")
cumulative_incidence.head()

   Year    State  Months  Year Born  Cumulative Incidence   LI        UI
0  2022  Arizona       1       2014                   0.0  0.0  0.572255
1  2022  Arizona       2       2014                   0.0  0.0  0.572255
2  2022  Arizona       3       2014                   0.0  0.0  0.572255
3  2022  Arizona       4       2014                   0.0  0.0  0.572255
4  2022  Arizona       5       2014                   0.0  0.0  0.572255

In [37]:
# Read Confidence Interval
confidence_interval = pd.read_csv("../data/Estimates for overall ASD prevalence in US over time with or without confidence interval__p_.csv")
confidence_interval.head()

,State,Denominator,"Prevalence Estimates per 1,000 Children",Lower CI,Upper CI,Prevalence Range,Show Lower and Upper CI,Year,Data Set
0,Alabama,35472.0,3.3,2.7,3.9,<10,Yes,2002,ADDM Network*
1,Alabama,11676.0,4.6,3.5,6.0,<10,Yes,2004,ADDM Network*
2,Alabama,35126.0,6.0,5.3,6.9,<10,Yes,2006,ADDM Network*
3,Alabama,36566.0,4.8,4.1,5.5,<10,Yes,2008,ADDM Network*
4,Alabama,21833.0,5.7,4.8,6.8,<10,Yes,2010,ADDM Network*

In [39]:
# Read Prevalence Estimates by Geographic Area
geography = pd.read_csv("../data/Prevalence Estimates by Geographic Area.csv")
geography.head()

,State,Denominator,"Prevalence Estimates per 1,000 Children",Lower CI,Upper CI,Prevalence Range,Show Lower and Upper CI,Year,Data Set
0,Alabama,35472.0,3.3,2.7,3.9,<10,Yes,2002,ADDM Network*
1,Alabama,11676.0,4.6,3.5,6.0,<10,Yes,2004,ADDM Network*
2,Alabama,35126.0,6.0,5.3,6.9,<10,Yes,2006,ADDM Network*
3,Alabama,36566.0,4.8,4.1,5.5,<10,Yes,2008,ADDM Network*
4,Alabama,21833.0,5.7,4.8,6.8,<10,Yes,2010,ADDM Network*

In [45]:
# Read Prevalence Estimates by Race_Ethnicity
ethnicity = pd.read_csv("../data/Prevalence Estimates by Race_Ethnicity.csv")
ethnicity.head()

,Year,State,White,White Lower CI,White Upper CI,Black,Black Lower CI,Black Upper CI,Hispanic,Hispanic Lower CI,Hispanic Upper CI,Asian or Pacific Islander,Asian or Pacific Islander Lower CI,Asian or Pacific Islander Upper CI,American Indian or Alaska Native,American Indian or Alaska Native Lower CI,American Indian or Alaska Native Upper CI,Multiracial,Multiracial Lower CI,Multiracial Upper CI
0,2000,Alabama,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2000,Arizona,8.6,7.5,9.8,7.3,4.4,12.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2000,Arkansas,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2000,California,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2000,Colorado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [47]:
# Read Prevalence Estimates by Gender
gender = pd.read_csv("../data/Prevalence Estimates by Sex.csv")
gender.head()

,Year,State,Boys,Boys Lower CI,Boys Upper CI,Girls,Girls Lower CI,Girls Upper CI
0,2000,Alabama,NaN,NaN,NaN,NaN,NaN,NaN
1,2000,Arizona,9.7,8.5,11.1,3.2,2.5,4.0
2,2000,Arkansas,NaN,NaN,NaN,NaN,NaN,NaN
3,2000,California,NaN,NaN,NaN,NaN,NaN,NaN
4,2000,Colorado,NaN,NaN,NaN,NaN,NaN,NaN

In [49]:
# Read Prevalence Estimates Over Time
overtime = pd.read_csv("../data/Prevalence Estimates Over Time.csv")
overtime.head()

,State,Denominator,"Prevalence Estimates per 1,000 Children",Lower CI,Upper CI,Prevalence Range,Show Lower and Upper CI,Year,Data Set
0,Alabama,35472.0,3.3,2.7,3.9,<10,Yes,2002,ADDM Network*
1,Alabama,11676.0,4.6,3.5,6.0,<10,Yes,2004,ADDM Network*
2,Alabama,35126.0,6.0,5.3,6.9,<10,Yes,2006,ADDM Network*
3,Alabama,36566.0,4.8,4.1,5.5,<10,Yes,2008,ADDM Network*
4,Alabama,21833.0,5.7,4.8,6.8,<10,Yes,2010,ADDM Network*