# Analyzing the Autism Prevalence

In [2]:
# Import Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re
from datetime import datetime

Read csv files to Dataframe

In [4]:
# Read Prevalence Estimates by Race_Ethnicity
ethnicity = pd.read_csv("../data/Prevalence Estimates by Race_Ethnicity.csv")
ethnicity.head()

,Year,State,White,White Lower CI,White Upper CI,Black,Black Lower CI,Black Upper CI,Hispanic,Hispanic Lower CI,Hispanic Upper CI,Asian or Pacific Islander,Asian or Pacific Islander Lower CI,Asian or Pacific Islander Upper CI,American Indian or Alaska Native,American Indian or Alaska Native Lower CI,American Indian or Alaska Native Upper CI,Multiracial,Multiracial Lower CI,Multiracial Upper CI
0,2000,Alabama,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2000,Arizona,8.6,7.5,9.8,7.3,4.4,12.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2000,Arkansas,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2000,California,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2000,Colorado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
# Read Prevalence Estimates by Gender
gender = pd.read_csv("../data/Prevalence Estimates by Sex.csv")
gender.head()

,Year,State,Boys,Boys Lower CI,Boys Upper CI,Girls,Girls Lower CI,Girls Upper CI
0,2000,Alabama,NaN,NaN,NaN,NaN,NaN,NaN
1,2000,Arizona,9.7,8.5,11.1,3.2,2.5,4.0
2,2000,Arkansas,NaN,NaN,NaN,NaN,NaN,NaN
3,2000,California,NaN,NaN,NaN,NaN,NaN,NaN
4,2000,Colorado,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
gender_etnicity = pd.merge(gender, ethnicity, on= ["Year","State"], how = "left")
gender_etnicity

,Year,State,Boys,Boys Lower CI,Boys Upper CI,Girls,Girls Lower CI,Girls Upper CI,White,White Lower CI,...,Hispanic Upper CI,Asian or Pacific Islander,Asian or Pacific Islander Lower CI,Asian or Pacific Islander Upper CI,American Indian or Alaska Native,American Indian or Alaska Native Lower CI,American Indian or Alaska Native Upper CI,Multiracial,Multiracial Lower CI,Multiracial Upper CI
0,2000,Alabama,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2000,Arizona,9.7,8.5,11.1,3.2,2.5,4.0,8.6,7.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2000,Arkansas,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2000,California,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2000,Colorado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
259,2022,Colorado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
260,2022,Florida,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
261,2022,North Carolina,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
262,2022,South Carolina,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
263,2022,West Virginia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN